from _typeshed import Incomplete

toc_properties: Incomplete

class ObjectPath:
    group: Incomplete
    channel: Incomplete
    def __init__(self, *path_components) -> None: ...
    @property
    def is_root(self): ...
    @property
    def is_group(self): ...
    @property
    def is_channel(self): ...
    def group_path(self): ...
    @staticmethod
    def from_string(path_string): ...
