from _typeshed import Incomplete
from collections.abc import Generator

log: Incomplete

class TdmsReader:
    object_metadata: Incomplete
    tdms_version: Incomplete
    def __init__(self, tdms_file) -> None: ...
    def close(self) -> None: ...
    def read_metadata(self, require_segment_indexes: bool = ...) -> None: ...
    def read_raw_data(self) -> Generator[Incomplete, None, None]: ...
    def read_raw_data_for_channel(
        self, channel_path, offset: int = ..., length: Incomplete | None = ...
    ) -> Generator[Incomplete, None, None]: ...
    def read_channel_chunk_for_index(self, channel_path, index): ...
    def is_index_file_only(self): ...

class ObjectMetadata:
    properties: Incomplete
    data_type: Incomplete
    scaler_data_types: Incomplete
    num_values: int
    def __init__(self) -> None: ...
