import pathlib
from typing import Union

from .types import TdmsType

file_path = Union[str, pathlib.Path]

def main() -> None: ...
def tdmsinfo(file: file_path, show_properties: bool = ...) -> None: ...
def display_properties(tdms_object: TdmsType, level: int) -> None: ...
def display(s: str, level: int) -> None: ...
