from typing import Any

import numpy as np

EPOCH: np.datetime64

class TdmsTimestamp:
    seconds: int
    second_fractions: float
    def __init__(self, seconds: int, second_fractions: float) -> None: ...
    def as_datetime64(self, resolution: str = ...) -> np.datetime64: ...
    def as_datetime(self): ...

class TimestampArray(np.ndarray):
    def __new__(cls, input_array): ...
    def __array_finalize__(self, obj: np.ndarray[Any, Any]) -> None: ...
    def __getitem__(self, item): ...
    @property
    def seconds(self): ...
    @property
    def second_fractions(self): ...
    def as_datetime64(self, resolution: str = ...) -> np.datetime64: ...
