def from_tdms_file(tdms_file, time_index: bool = ..., absolute_time: bool = ..., scaled_data: bool = ...): ...
def from_group(group, time_index: bool = ..., absolute_time: bool = ..., scaled_data: bool = ...): ...
def from_channel(channel, time_index: bool = ..., absolute_time: bool = ..., scaled_data: bool = ...): ...
